services:
  users-db-qa:
  image: postgres:16
  container_name: users-db-qa

  environment:
    POSTGRES_DB: usersdb_qa
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres123

  ports:
    - "5435:5432"

  networks:
    - qa-net

  turnos-db-qa:
  image: postgres:16
  container_name: turnos-db-qa

  environment:
    POSTGRES_DB: turnosdb_qa
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres123

  ports:
    - "5436:5432"

  networks:
    - qa-net

 users-service-qa:
  build:
    context: ./backend/users-service
    dockerfile: Dockerfile

  container_name: users-service-qa

  depends_on:
    - users-db-qa

  environment:
    SPRING_PROFILES_ACTIVE: qa

  ports:
    - "8181:8181"

  networks:
    - qa-net

  turnos-service-qa:
  build:
    context: ./backend/turnos-service
    dockerfile: Dockerfile

  container_name: turnos-service-qa

  depends_on:
    - turnos-db-qa

  environment:
    SPRING_PROFILES_ACTIVE: qa

  ports:
    - "8182:8182"

  networks:
    - qa-net

  api-gateway-qa:
    build:
      context: ./backend/api-gateway
    container_name: api-gateway-qa
    depends_on:
      - users-service-qa
      - turnos-service-qa
    environment:
      SPRING_PROFILES_ACTIVE: qa
    ports:
      - "8180:8180"
    networks:
      - qa-net

volumes:
  usersdb_qa_data:
  turnosdb_qa_data:

networks:
  qa-net: