spring.application.name=notifications-service

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/notificationsdb
spring.datasource.username=postgres
spring.datasource.password=yeison

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml