server:
  port: ${PORT:8284}

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27019/auditdb_main}

management:
  endpoints:
    web:
      exposure:
        include: health,info
