server.port=8081
spring.application.name=users-service-develop

spring.datasource.url=jdbc:postgresql://localhost:5432/usersdb_develop
spring.datasource.username=postgres
spring.datasource.password=yeison

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml