server.port=${PORT:8282}
spring.application.name=turnos-service-main

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://turnos-db-main:5432/turnosdb_main}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres123}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml