server:
  port: ${PORT:8280}

spring:
  application:
    name: api-gateway-main

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: ${USERS_SERVICE_URL:http://users-service-main:8281}
          predicates:
            - Path=/users/**

        - id: turnos-service
          uri: ${TURNOS_SERVICE_URL:http://turnos-service-main:8282}
          predicates:
            - Path=/turnos/**

        - id: notifications-service
          uri: ${NOTIFICATIONS_SERVICE_URL:http://notifications-service-main:8283}
          predicates:
            - Path=/notifications/**

        - id: audit-service
          uri: ${AUDIT_SERVICE_URL:http://audit-service-main:8284}
          predicates:
            - Path=/audit/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"