server:
  port: 8180

spring:
  application:
    name: api-gateway-qa

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://users-service-qa:8181
          predicates:
            - Path=/users,/users/**

        - id: turnos-service
          uri: http://turnos-service-qa:8182
          predicates:
            - Path=/turnos,/turnos/**

        - id: notifications-service
          uri: http://notifications-service-qa:8183
          predicates:
            - Path=/notifications,/notifications/**

        - id: audit-service
          uri: http://audit-service-qa:8184
          predicates:
            - Path=/audit,/audit/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4210"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"